extract: clean
	open output_demo_fiq_root.zip output_demo_mcq_root.zip output_demo.zip output_demo_mq_root.zip

clean:
	-rm -r  output_demo_fiq_root output_demo_mcq_root output_demo output_demo_mq_root


distclean: clean
	-rm output_demo_fiq_root.zip output_demo_mcq_root.zip output_demo.zip output_demo_mq_root.zip

.PHONY: clean extract distclean
