extract: clean
	open output_demo_fiq_root.zip output_demo_mcq_root.zip output_demo.zip

clean:
	-rm -r  output_demo_fiq_root output_demo_mcq_root output_demo


distclean: clean
	-rm output_demo_fiq_root.zip output_demo_mcq_root.zip output_demo.zip

.PHONY: clean extract distclean
